// For usage examples check out FormatTable.hpp.

// clang-format off
//          RHI                                        Bit        V ulkan
RHI_XACCESS(ACCESS_NONE,                               (1U << 0),  VK_ACCESS_2_NONE)
RHI_XACCESS(ACCESS_INDIRECT_COMMAND_READ_BIT,          (1U << 1),  VK_ACCESS_2_INDIRECT_COMMAND_READ_BIT)
RHI_XACCESS(ACCESS_INDEX_READ_BIT,                     (1U << 2),  VK_ACCESS_2_INDEX_READ_BIT)
RHI_XACCESS(ACCESS_VERTEX_ATTRIBUTE_READ_BIT,          (1U << 3),  VK_ACCESS_2_VERTEX_ATTRIBUTE_READ_BIT)
RHI_XACCESS(ACCESS_UNIFORM_READ_BIT,                   (1U << 4),  VK_ACCESS_2_UNIFORM_READ_BIT)
RHI_XACCESS(ACCESS_INPUT_ATTACHMENT_READ_BIT,          (1U << 5),  VK_ACCESS_2_INPUT_ATTACHMENT_READ_BIT)
RHI_XACCESS(ACCESS_SHADER_READ_BIT,                    (1U << 6),  VK_ACCESS_2_SHADER_READ_BIT)
RHI_XACCESS(ACCESS_SHADER_WRITE_BIT,                   (1U << 7),  VK_ACCESS_2_SHADER_WRITE_BIT)
RHI_XACCESS(ACCESS_COLOR_ATTACHMENT_READ_BIT,          (1U << 8),  VK_ACCESS_2_COLOR_ATTACHMENT_READ_BIT)
RHI_XACCESS(ACCESS_COLOR_ATTACHMENT_WRITE_BIT,         (1U << 9),  VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT)
RHI_XACCESS(ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT,  (1U << 10), VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_READ_BIT)
RHI_XACCESS(ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT, (1U << 11), VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT)
RHI_XACCESS(ACCESS_TRANSFER_READ_BIT,                  (1U << 12), VK_ACCESS_2_TRANSFER_READ_BIT)
RHI_XACCESS(ACCESS_TRANSFER_WRITE_BIT,                 (1U << 13), VK_ACCESS_2_TRANSFER_WRITE_BIT)
RHI_XACCESS(ACCESS_HOST_READ_BIT,                      (1U << 14), VK_ACCESS_2_HOST_READ_BIT)
RHI_XACCESS(ACCESS_HOST_WRITE_BIT,                     (1U << 15), VK_ACCESS_2_HOST_WRITE_BIT)
RHI_XACCESS(ACCESS_MEMORY_READ_BIT,                    (1U << 16), VK_ACCESS_2_MEMORY_READ_BIT)
RHI_XACCESS(ACCESS_MEMORY_WRITE_BIT,                   (1U << 17), VK_ACCESS_2_MEMORY_WRITE_BIT)
RHI_XACCESS(ACCESS_SHADER_SAMPLED_READ_BIT,            (1U << 18), VK_ACCESS_2_SHADER_SAMPLED_READ_BIT)
RHI_XACCESS(ACCESS_SHADER_STORAGE_READ_BIT,            (1U << 19), VK_ACCESS_2_SHADER_STORAGE_READ_BIT)
RHI_XACCESS(ACCESS_SHADER_STORAGE_WRITE_BIT,           (1U << 20), VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT)
// clang-format on
#undef RHI_XACCESS
