// Using X-macro to define a 1D LUT for each API, just to keep changes in sync.
// Example usage:
//
// static const VkFormat sTable[] =
// {
// #define RHI_XFMT(rhiFormat, vulkanFormat) vulkanFormat,
// #include "FormatTable.hpp"
// };

// clang-format off
//       RHI                             Vulkan
RHI_XFMT(FORMAT_UNDEFINED,               VK_FORMAT_UNDEFINED)
RHI_XFMT(FORMAT_R8_UNORM,                VK_FORMAT_R8_UNORM)
RHI_XFMT(FORMAT_R8G8B8A8_UNORM,          VK_FORMAT_R8G8B8A8_UNORM)
RHI_XFMT(FORMAT_R8G8B8A8_SNORM,          VK_FORMAT_R8G8B8A8_SNORM)
RHI_XFMT(FORMAT_B8G8R8A8_UNORM,          VK_FORMAT_B8G8R8A8_UNORM)
RHI_XFMT(FORMAT_R16_SFLOAT,              VK_FORMAT_R16_SFLOAT)
RHI_XFMT(FORMAT_R16G16_SFLOAT,           VK_FORMAT_R16G16_SFLOAT)
RHI_XFMT(FORMAT_R32_SFLOAT,              VK_FORMAT_R32_SFLOAT)
RHI_XFMT(FORMAT_R32G32_UINT,             VK_FORMAT_R32G32_UINT)
RHI_XFMT(FORMAT_R32G32_SFLOAT,           VK_FORMAT_R32G32_SFLOAT)
RHI_XFMT(FORMAT_E5B9G9R9_UFLOAT_PACK32,  VK_FORMAT_E5B9G9R9_UFLOAT_PACK32)
RHI_XFMT(FORMAT_B10G11R11_UFLOAT_PACK32, VK_FORMAT_B10G11R11_UFLOAT_PACK32)
RHI_XFMT(FORMAT_D32_SFLOAT,              VK_FORMAT_D32_SFLOAT)
RHI_XFMT(FORMAT_D16_UNORM,               VK_FORMAT_D16_UNORM)
RHI_XFMT(FORMAT_S8_UINT,                 VK_FORMAT_S8_UINT)
RHI_XFMT(FORMAT_BC7_UNORM_BLOCK,         VK_FORMAT_BC7_UNORM_BLOCK)
RHI_XFMT(FORMAT_BC7_SRGB_BLOCK,          VK_FORMAT_BC7_SRGB_BLOCK)
RHI_XFMT(FORMAT_BC5_UNORM_BLOCK,         VK_FORMAT_BC5_UNORM_BLOCK)
// clang-format on
#undef RHI_XFMT
