// For usage examples check out FormatTable.hpp.

// clang-format off
//         RHI                                Bit         Vulkan
RHI_XSTAGE(STAGE_NONE,                        (1U << 0),  VK_PIPELINE_STAGE_2_NONE)
RHI_XSTAGE(STAGE_DRAW_INDIRECT_BIT,           (1U << 1),  VK_PIPELINE_STAGE_2_DRAW_INDIRECT_BIT)
RHI_XSTAGE(STAGE_VERTEX_INPUT_BIT,            (1U << 2),  VK_PIPELINE_STAGE_2_VERTEX_INPUT_BIT)
RHI_XSTAGE(STAGE_VERTEX_SHADER_BIT,           (1U << 3),  VK_PIPELINE_STAGE_2_VERTEX_SHADER_BIT)
RHI_XSTAGE(STAGE_FRAGMENT_SHADER_BIT,         (1U << 4),  VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT)
RHI_XSTAGE(STAGE_EARLY_FRAGMENT_TESTS_BIT,    (1U << 5),  VK_PIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BIT)
RHI_XSTAGE(STAGE_LATE_FRAGMENT_TESTS_BIT,     (1U << 6),  VK_PIPELINE_STAGE_2_LATE_FRAGMENT_TESTS_BIT)
RHI_XSTAGE(STAGE_COLOR_ATTACHMENT_OUTPUT_BIT, (1U << 7),  VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT)
RHI_XSTAGE(STAGE_COMPUTE_SHADER_BIT,          (1U << 8),  VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT)
RHI_XSTAGE(STAGE_ALL_TRANSFER_BIT,            (1U << 9),  VK_PIPELINE_STAGE_2_ALL_TRANSFER_BIT)
RHI_XSTAGE(STAGE_TRANSFER_BIT,                (1U << 10), VK_PIPELINE_STAGE_2_TRANSFER_BIT)
RHI_XSTAGE(STAGE_HOST_BIT,                    (1U << 11), VK_PIPELINE_STAGE_2_HOST_BIT)
RHI_XSTAGE(STAGE_ALL_GRAPHICS_BIT,            (1U << 12), VK_PIPELINE_STAGE_2_ALL_GRAPHICS_BIT)
RHI_XSTAGE(STAGE_ALL_COMMANDS_BIT,            (1U << 13), VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT)
RHI_XSTAGE(STAGE_COPY_BIT,                    (1U << 14), VK_PIPELINE_STAGE_2_COPY_BIT)
RHI_XSTAGE(STAGE_RESOLVE_BIT,                 (1U << 15), VK_PIPELINE_STAGE_2_RESOLVE_BIT)
RHI_XSTAGE(STAGE_BLIT_BIT,                    (1U << 16), VK_PIPELINE_STAGE_2_BLIT_BIT)
RHI_XSTAGE(STAGE_CLEAR_BIT,                   (1U << 17), VK_PIPELINE_STAGE_2_CLEAR_BIT)
#undef RHI_XSTAGE
// clang-format on
