#pragma once

// Shared with C++.

#define VULKAN_ENABLE_DEBUG_UTILS

static const float RENDERER_NEAR_PLANE = 0.1f;
static const int RENDERER_MAX_FRAMES_IN_FLIGHT = 2;
static const int RENDERER_DEBUG_DRAW_RECT_MAX_COUNT = 4096;
static const float RENDERER_SHADOW_FAR_PLANE = 50.0f;
static const int RENDERER_SHADOW_MAP_CASCADE_COUNT = 4;
static const int RENDERER_SHADOW_MAP_DIMENSIONS = 2048; // TODO: 1536?
static const int RENDERER_SHADOW_MAP_JITTER_OFFSETS_SIZE = 16;
static const int RENDERER_SHADOW_MAP_JITTER_OFFSETS_SAMPLES_U = 8;
static const int RENDERER_SHADOW_MAP_JITTER_OFFSETS_SAMPLES_V = 8;
static const float RENDERER_ESM_EXPONENT = 10.0;

static const int RENDERER_CULL_WORKGROUP_SIZE = 64;
// TODO: why am I even keeping this separated?
static const int RENDERER_DEPTH_REDUCE_WORKGROUP_SIZE_X = 8;
static const int RENDERER_DEPTH_REDUCE_WORKGROUP_SIZE_Y = 8;
static const int RENDERER_SSAO_WORKGROUP_SIZE_X = 8;
static const int RENDERER_SSAO_WORKGROUP_SIZE_Y = 8;
static const int RENDERER_SSAO_BLUR_WORKGROUP_SIZE_X = 8;
static const int RENDERER_SSAO_BLUR_WORKGROUP_SIZE_Y = 8;
static const int RENDERER_SSAO_UPSAMPLE_WORKGROUP_SIZE_X = 8;
static const int RENDERER_SSAO_UPSAMPLE_WORKGROUP_SIZE_Y = 8;
static const int RENDERER_SHADOW_ESM_WORKGROUP_SIZE_X = 8;
static const int RENDERER_SHADOW_ESM_WORKGROUP_SIZE_Y = 8;
static const int RENDERER_SHADOW_ESM_BLUR_WORKGROUP_SIZE_X = 8;
static const int RENDERER_SHADOW_ESM_BLUR_WORKGROUP_SIZE_Y = 8;
static const int RENDERER_FOG_WORKGROUP_SIZE_X = 8;
static const int RENDERER_FOG_WORKGROUP_SIZE_Y = 8;
static const int RENDERER_RENDER_WORKGROUP_SIZE_X = 8;
static const int RENDERER_RENDER_WORKGROUP_SIZE_Y = 8;
static const int RENDERER_TAA_RESOLVE_WORKGROUP_SIZE_X = 8;
static const int RENDERER_TAA_RESOLVE_WORKGROUP_SIZE_Y = 8;
